# Generated by Django 5.2.3 on 2025-06-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
    ]
