# Generated by Django 5.2.3 on 2025-06-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_myuser_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
