# Generated by Django 5.2.3 on 2025-06-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_courses_myuser_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
    ]
